language: ruby
rvm:
  - 1.9.3

before_install:
  - gem install bundler --pre

before_script:
  - psql -c 'create database minefold_test;' -U postgres

env:
  - ansi=true
  - rpt=pretty
  - backtrace=99

script:
  - bundle exec rake test
