language: ruby
rvm:
  - 1.9.3

before_install:
  - gem install bundler --pre

before_script:
  - psql -c 'create database minefold_test;' -U postgres
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare

env:
  - ansi=true rpt=pretty backtrace=99 STRIPE_PUBLISHABLE=pk_zpPW1A05d5zpNjFcafVXdFhqFsQpX STRIPE_SECRET=hbppjx2CB6XAebJNDVWEE6j7xBtTZy5k
