language: ruby
rvm:
  - 1.9.3

services:
  - redis-server

before_install:
  - apt-get install libicu-dev
  - gem install bundler --pre

before_script:
  - psql -c 'create database minefold_test;' -U postgres
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
