module MinefoldBlacklist
  def self.usernames
    %w{ about
        account
        admin
        api
        better
        blog
        cache
        changelog
        codereview
        compare
        confirm
        enterprise
        gist
        help
        hosting
        jobs
        lists
        login
        logout
        mine
        news
        order
        orders
        organizations
        plans
        press
        pricing
        privacy
        popular
        projects
        security
        shop
        signin
        signup
        stories
        status
        stripe
        styleguide
        terms
        tour
        translations
        user
        users
        wiki
        worlds
    }
  end
end
