development:
  bucket: minefold.import
  access_key_id: AKIAJPN5IJVEBB2QE35A
  secret_access_key: 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
  max_file_size: 10485760
  acl: public-read

test:
  bucket: minefold.import
  access_key_id: AKIAJPN5IJVEBB2QE35A
  secret_access_key: 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
  max_file_size: 10485760
  acl: public-read

production:
  bucket: minefold.import
  access_key_id: AKIAJPN5IJVEBB2QE35A
  secret_access_key: 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
  max_file_size: 10485760
  acl: public-read

staging:
  bucket: minefold.import
  access_key_id: AKIAJPN5IJVEBB2QE35A
  secret_access_key: 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
  max_file_size: 10485760
  acl: public-read
