development:
  host: localhost
  database: minefold

test:
  host: localhost
  database: minefold_test

staging:
  uri: <%= ENV['MONGOHQ_URL'] || ENV['DATABASE_URL'] %>

production:
  uri: <%= ENV['MONGOHQ_URL'] || ENV['DATABASE_URL'] %>
