development:
  host: localhost
  database: minefold

test:
  host: localhost
  database: minefold_test

staging:
  host: <%= ENV['MONGOHQ_URL'] || 'mongodb://user:pass@127.0.0.1/dbname' %>

production:
  uri: <%= ENV['MONGOHQ_URL'] || 'mongodb://user:pass@127.0.0.1/dbname' %>
