development:
  host: localhost
  database: minefold
  identity_map_enabled: true

test:
  host: localhost
  database: minefold_test
  identity_map_enabled: true

staging:
  identity_map_enabled: true
  uri: <%= ENV['MONGOHQ_URL'] || 'mongodb://heroku:5fb18d7c862247982989d24305e3725c@staff.mongohq.com:10022/app650848' %>

production:
  identity_map_enabled: true
  uri: <%= ENV['MONGOHQ_URL'] || 'mongodb://heroku:15a8f355615361aeda458c6d887aada2@staff.mongohq.com:10023/app650862' %>
