development:
  host: localhost
  database: minefold
  identity_map_enabled: true
  persist_in_safe_mode: true
  max_retries_on_connection_failure: 3

test:
  host: localhost
  database: minefold_test
  identity_map_enabled: true
  persist_in_safe_mode: true
  max_retries_on_connection_failure: 3

staging:
  uri: <%= ENV['MONGOHQ_URI'] %>
  identity_map_enabled: true
  persist_in_safe_mode: true
  max_retries_on_connection_failure: 3

production:
  uri: <%= ENV['MONGOHQ_URI'] %>
  identity_map_enabled: true
  persist_in_safe_mode: true
  max_retries_on_connection_failure: 3
  slave_ok: true
