development:
  sessions:
    default:
      database: minefold
      hosts:
        - localhost:27017
      options:
        identity_map_enabled: true

test:
  sessions:
    default:
      database: minefold_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        identity_map_enabled: true

staging:
  sessions:
    default:
      uri: <%= ENV['MONGO_URI'] %>
      options:
        consistency: :eventual
        identity_map_enabled: true


<%
  if ENV['MONGO_URI']
    uri = Mongo::URIParser.new(ENV['MONGO_URI'])
    nodes = uri.nodes
    auth = uri.auths.first
%>
production:
  sessions:
    default:
      database: <%= auth['db_name'] %>
      username: <%= auth['username'] %>
      password: <%= auth['password'] %>
      hosts:
      <% nodes.each do |node| %>
        - <%= node[0] %>:<%= node[1] %>
      <% end %>
      options:
        consistency: :eventual
        identity_map_enabled: true
<% end %>
