development:
  sessions:
    default:
      database: minefold
      hosts:
        - localhost:27017
      options:
        identity_map_enabled: true

test:
  sessions:
    default:
      database: minefold_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        identity_map_enabled: true

staging:
  sessions:
    default:
      uri: <%= ENV['MONGO_URI'] %>
      options:
        consistency: :eventual
        identity_map_enabled: true

production:
  sessions:
    default:
      uri: <%= ENV['MONGO_URI'] %>
      options:
        consistency: :eventual
        identity_map_enabled: true
