development:
  host: localhost
  database: minefold
  identity_map_enabled: true

test:
  host: localhost
  database: minefold_test
  identity_map_enabled: true

staging:
  uri: <%= ENV['MONGOLAB_URI'] || 'mongodb://heroku_app650862:96gg63iarmqm0tuq46knv4a8mb@dbh18.mongolab.com:27187/heroku_app650862' %>
  identity_map_enabled: true

production:
  uri: <%= ENV['MONGOLAB_URI'] || 'mongodb://heroku_app650862:96gg63iarmqm0tuq46knv4a8mb@dbh18.mongolab.com:27187/heroku_app650862' %>
  identity_map_enabled: true
