development:
  sessions:
    default:
      database: minefold
      hosts:
        - localhost:27017
      options:
        identity_map_enabled: true

test:
  sessions:
    default:
      database: minefold_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        identity_map_enabled: true

staging:
  sessions:
    default:
      uri: <%= ENV['MONGO_URI'] %>
      options:
        consistency: :eventual
        identity_map_enabled: true

production:
  sessions:
    default:
      database: production
      username: minefold
      password: Aru06kAy8xE2
      hosts:
        - - sun.member0.mongohq.com
          - 10018
        - sun.member1.mongohq.com
          - 10018
      options:
        skip_version_check: true
        identity_map_enabled: true
        safe: true
